[package]
name = "Design"
version = "1.0.0"
description = "Simx Era Design"
authors = ["NJ Labs"]
edition = "2021"

[lib]
name = "design_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-http = "2"
tauri-plugin-os = "2"
tauri-plugin-store = "2"
tauri-plugin-log = "2"
tauri-plugin-upload = "2"

[target.'cfg(windows)'.dependencies]
# 加载dll，仅在windows平台下生效
libloader = "0.1.4"

[target.'cfg(unix)'.dependencies]
# 加载 so和dylib，仅在unix平台下生效（linux、macos）
libloading = "0.8.5"

# 优化配置（一般不需要修改）
[profile.release]
codegen-units = 1 # 允许 LLVM 执行更好地优化。
lto = true # 启用链接时优化。
opt-level = "s" # 优先考虑小的二进制文件大小。如果您更喜欢速度，请使用 `3`。
panic = "abort" # 通过禁用 panic 处理程序来提高性能。
strip = true # 确保移除调试符号。
