/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollapsibleMenu: typeof import('./src/components/CollapsibleMenu.vue')['default']
    DropzoneBackground: typeof import('./src/components/DropzoneBackground.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExtensionItem: typeof import('./src/components/ExtensionItem.vue')['default']
    ExtensionList: typeof import('./src/components/ExtensionList.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    NaveDialog: typeof import('./src/components/NaveDialog.vue')['default']
    NaveItem: typeof import('./src/components/NaveItem.vue')['default']
    NaveMenuButtom: typeof import('./src/components/NaveMenuButtom.vue')['default']
    NavePanel: typeof import('./src/components/NavePanel.vue')['default']
  }
}
